export const productValues = {
  title_en: "",
  title_ar: "",
  description_en: "",
  description_ar: "",
  priceBeforeDiscount: 1,
  quantity: 0,
  images: [],
  paymentType: "",
  keywords: [],
  category: "",
  subCategory: "",
  weight: 1,
  qualities: [],
  generalQualities: [],
  attributes: [],
  title_meta: "",
  desc_meta: "",
  link: "",
  title: "",
  message: "",
  shippingPrice: 0,
  subSubCategory: "",
  repositoryId: "",
};

export const productQualityValues = {
  key_en: "",
  key_ar: "",
  values: [],
};
